---
# Title The Generator
title:     Acronym Generator

# Use this for an analogy, used for update page. EX: What is TRBMB?
shortname: AcronymGen

# Who made the generator?
creator:   Chewsterchew

# Repo URL: THIS MUST BE Name/Repo. Ex: Chewsterchew/TRBMB-Gen
repourl:   Chewsterchew/AcronymGenerator

# Footer Extra Content
## You'll probably want to delete this (unless you have a twitter and bot for it too?)
#footer-extra: >
  
